# -*- coding: utf-8 -*-
"""Portfolio Work 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbrXk5sSyYoE1OdIkTJ6yXdrVcXQ_DPG
"""

#This simulation models projectile motion of a particle (using the Euler
#method) without the effect of bouncing and drag. Multiple angles of
#projection can be displayed
import numpy as np
import matplotlib.pyplot as plt

import seaborn
seaborn.set_style("whitegrid")
plt.rcParams.update({'font.size': 7})

#Input Initial Conditions
#Enter Initial X position (m) - away from origin (0,0)
rx_initial = 0
#Enter Initial Y position (m) - away from origin (0,0)
ry_initial = 0
#Enter (one or more) angle(s) of projection from the horizontal in degrees,
#seperated with commas with square brackets around them (e.g., [10, 20, 30])
theta_degs = [30, 60]
#Enter initial absolute velocity (metres per second)
v_initial = 10
#Enter simulation time (seconds) - Simulation will end as particle hits ground
tf= 10
#Enter step size (seconds)
dt = 0.01

#Constant
g = 9.81

def simulate_projectile(dt, theta_deg): #modelling it as a functiom of angle
#and time
  t_current = 0
  theta_rad = np.radians(theta_deg)
  rx_current = rx_initial
  ry_current = ry_initial

  vx_current = v_initial * np.cos(theta_rad)
  vy_current = v_initial * np.sin(theta_rad)


  ts = [t_current]
  rxs = [rx_current]
  rys = [ry_current]
  vxs = [vx_current]
  vys = [vy_current]

  while t_current < tf :
      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt


      vx_new = vx_current
      vy_new = vy_current - g * dt

      if ry_new < 0:
            ry_new = 0
            break
      if rx_new < 0:
            rx_new = 0
            break
      t_current += dt

      rx_current = rx_new
      ry_current = ry_new

      vx_current = vx_new
      vy_current = vy_new

      ts.append(t_current)
      rxs.append(rx_new)
      rys.append(ry_new)
      vxs.append(vx_new)
      vys.append(vy_new)

  ts = np.array(ts)
  rxs = np.array(rxs)
  rys = np.array(rys)
  vxs = np.array(vxs)
  vys = np.array(vys)
  vabs = np.sqrt(vxs**2 + vys**2)

  return ts, rxs, rys, vabs

colormaps = ['magma', 'mako', 'inferno', 'viridis', 'plasma']

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

scatter_xy_list = []


for idx, theta_deg in enumerate(theta_degs):
  ts, rxs, rys, vabs = simulate_projectile(dt=dt, theta_deg=theta_deg)


  cmap = colormaps[idx % len(colormaps)]

  axes[0].scatter(ts, rxs,  c=vabs, cmap=cmap)
  axes[0].set(xlabel= "Time (s)", ylabel="X Position (m)")

  axes[1].scatter(ts, rys,  c=vabs, cmap=cmap)
  axes[1].set(xlabel= "Time (s)", ylabel="Y Position (m)")

  scatter_xy=axes[2].scatter(rxs, rys, c=vabs, cmap=cmap)
  axes[2].set(xlabel= "X Position (m)", ylabel="Y Position (m)")
  scatter_xy_list.append(scatter_xy)


#set colour bars for each angle plotted with the far right colour bar being
#the only labelled one
for idx, (scatter, theta_deg) in enumerate(zip(scatter_xy_list, theta_degs)):
    cbar = fig.colorbar(scatter, ax=axes, orientation='vertical', pad=0.02, fraction=0.046)
    cbar.set_label(f'Absolute Velocity (m/s) - θ = {theta_degs[idx]}°')
    if idx > 0:
      cbar.set_ticks([])

# Calculate max height and distance
def calculate_max_height_and_distance(ts, rys, rxs):
    max_height = np.max(rys)
    distance_travelled = rxs[-1]
    time_of_max_height = ts[np.argmax(rys)]
    return max_height, distance_travelled, time_of_max_height

for idx, theta_deg in enumerate(theta_degs):
    ts, rxs, rys, _ = simulate_projectile(dt, theta_deg)
    max_height, distance_travelled, time_max_height = calculate_max_height_and_distance(ts, rys, rxs)
    print(f"Where \u03B8 = {theta_deg}°")
    print(f"Maximum Height Reached: {max_height:.2f} m at Time: {time_max_height:.2f} s")
    print(f"Maximum Distance before hitting the ground: {distance_travelled:.2f} m")


#Graphing layout - Adjustable
plt.subplots_adjust(left=0, right=0.8)
plt.show()

#This simulation models projectile motion of a particle (using the Euler
#method) without the effect of bouncing and drag.
#Multiple time steps can be displayed.
import numpy as np
import matplotlib.pyplot as plt

import seaborn
seaborn.set_style("whitegrid")
plt.rcParams.update({'font.size': 7})

#Input Initial Conditions
#Enter Initial X position (m) - away from origin (0,0)
rx_initial = 0
#Enter Initial Y position (m) - away from origin (0,0)
ry_initial = 0
#Enter angle of projection from horizontal (degrees)
theta_deg = 45
#Enter initial absolute velocity (metres per second)
v_initial = 2
#Enter simulation time (seconds) - Simulation will end as particle hits ground
tf = 10
# Enter multiple step sizes in seconds, seperated with commas with square
#brackets around them (e.g., [0.1, 0.01, 0.001])
dts= [0.001, 0.01, 0.1]



#Constant
g = 9.81

def simulate_projectile(dt): #modelling it as a functiom of time

  t_current = 0
  theta_rad = np.radians(theta_deg)
  rx_current = rx_initial
  ry_current = ry_initial


  vx_current = v_initial * np.cos(theta_rad)
  vy_current = v_initial * np.sin(theta_rad)



  ts = [t_current]
  rxs = [rx_current]
  rys = [ry_current]
  vxs = [vx_current]
  vys = [vy_current]

  while t_current < tf :
      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt

      vx_new = vx_current + 0 * dt
      vy_new = vy_current - g * dt

      if ry_new < 0:
            ry_new = 0
            break
      if rx_new < 0:
            rx_new = 0
            break
      t_current += dt


      rx_current = rx_new
      ry_current = ry_new

      vx_current = vx_new
      vy_current = vy_new

      ts.append(t_current)
      rxs.append(rx_new)
      rys.append(ry_new)
      vxs.append(vx_new)
      vys.append(vy_new)

  ts = np.array(ts)
  rxs = np.array(rxs)
  rys = np.array(rys)
  vxs = np.array(vxs)
  vys = np.array(vys)
  vabs = np.sqrt(vxs**2 + vys**2)

  return ts, rxs, rys, vabs

colormaps = ['magma', 'mako', 'inferno', 'viridis', 'plasma']

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

scatter_xy_list = []



for idx, dt in enumerate(dts):
  ts, rxs, rys, vabs = simulate_projectile(dt=dt)

  cmap = colormaps[idx % len(colormaps)]

  axes[0].scatter(ts, rxs,  c=vabs, cmap=cmap)
  axes[0].set(xlabel= "Time (s)", ylabel="X Position (m)")

  axes[1].scatter(ts, rys,  c=vabs, cmap=cmap)
  axes[1].set(xlabel= "Time (s)", ylabel="Y Position (m)")

  scatter_xy=axes[2].scatter(rxs, rys, c=vabs, cmap=cmap)
  axes[2].set(xlabel= "X Position (m)", ylabel="Y Position (m)")
  scatter_xy_list.append(scatter_xy)


#set colour bars for each angle plotted with the far right colour bar
#being the only labelled one
for idx, (scatter, dt) in enumerate(zip(scatter_xy_list, dts)):
    cbar = fig.colorbar(scatter, ax=axes, orientation='vertical', pad=0.02, fraction=0.046)
    cbar.set_label(f'Absolute Velocity (m/s) - dt = {dts[idx]}s')
    if idx > 0:
        cbar.set_ticks([])


# Calculate max height and distance
def calculate_max_height_and_distance(ts, rys, rxs):
    max_height = np.max(rys)
    distance_travelled = rxs[-1]
    time_of_max_height = ts[np.argmax(rys)]
    return max_height, distance_travelled, time_of_max_height

for idx, dt in enumerate(dts):
    ts, rxs, rys, _ = simulate_projectile(dt)
    max_height, distance_travelled, time_max_height = calculate_max_height_and_distance(ts, rys, rxs)
    print(f"Where dt = {dt} s")
    print(f"Maximum Height Reached: {max_height:.2f} m at Time: {time_max_height:.2f} s")


#Graphing layout - Adjustable
plt.subplots_adjust(left=0, right=0.77)
plt.show()

#This simulation models projectile motion of a particle (using the Verlet
#and Euler method) without the effects of bouncing and drag
import numpy as np
import matplotlib.pyplot as plt

import seaborn
seaborn.set_style("whitegrid")

#Input Initial Conditions
#Enter Initial X position (m) - away from origin (0,0)
rx_initial = 0
#Enter Initial Y position (m) - away from origin (0,0)
ry_initial = 0
#Enter angle of projection from horizontal (degrees)
theta_deg = 45
#Enter initial absolute velocity (metres per second)
v_initial = 10
#Enter simulation time (seconds)
tf = 10
#Enter step size (seconds)
dt = 0.1



def simulate_projectile(dt, verlet=False):
  #modelling it as a functiom of time

  t_current = 0
  theta_rad = np.radians(theta_deg)
  rx_current = rx_initial
  ry_current = ry_initial

  vx_current = v_initial * np.cos(theta_rad)
  vy_current = v_initial * np.sin(theta_rad)

  g = 9.81

  ts = [t_current]
  rxs = [rx_current]
  rys = [ry_current]
  vxs = [vx_current]
  vys = [vy_current]

  while t_current < tf :
    if verlet:
      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt + (1/2) * -g * dt**2
      vx_new = vx_current + 0 * dt
      vy_new = vy_current - g * dt
    else:
      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt


      vx_new = vx_current + 0 * dt
      vy_new = vy_current - g * dt


    if ry_new < 0:
        ry_new = 0
        break
    if rx_new < 0:
        rx_new = 0
        break

    t_current += dt


    rx_current = rx_new
    ry_current = ry_new

    vx_current = vx_new
    vy_current = vy_new

    ts.append(t_current)
    rxs.append(rx_new)
    rys.append(ry_new)
    vxs.append(vx_new)
    vys.append(vy_new)

  ts = np.array(ts)
  rxs = np.array(rxs)
  rys = np.array(rys)
  vxs = np.array(vxs)
  vys = np.array(vys)
  vabs = np.sqrt(vxs**2 + vys**2)

  return ts, rxs, rys, vabs

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

dts = [dt]


for dt in dts:

  ts_noverlet, rxs_noverlet, rys_noverlet, vabs_noverlet = simulate_projectile(dt=dt, verlet=False)
  ts_verlet, rxs_verlet, rys_verlet, vabs_verlet = simulate_projectile(dt=dt, verlet=True)
  ts, rxs, rys, vabs = simulate_projectile(dt=dt)

  scatter_noverlet=axes[0].scatter(ts_noverlet, rxs_noverlet,  c=vabs_noverlet, alpha=0.7, cmap='viridis', label='Euler')
  scatter_verlet=axes[0].scatter(ts_verlet, rxs_verlet,  c=vabs_verlet, alpha=0.3, cmap='magma', label='Verlet')
  axes[0].set(xlabel= "Time (s)", ylabel="X Position (m)")



  scatter_noverlet=axes[1].scatter(ts_noverlet, rys_noverlet,  c=vabs_noverlet, alpha=0.7, cmap='viridis', label='Euler')
  scatter_verlet=axes[1].scatter(ts_verlet, rys_verlet,  c=vabs_verlet, alpha=0.3, cmap='magma', label='Verlet')
  axes[1].set(xlabel= "Time (s)", ylabel="Y Position (m)")


  scatter_noverlet=axes[2].scatter(rxs_noverlet, rys_noverlet,  c=vabs_noverlet, alpha=0.7, cmap='viridis', label='Euler')
  scatter_verlet=axes[2].scatter(rxs_verlet, rys_verlet,  c=vabs_verlet, alpha=0.3, cmap='magma', label='Verlet')
  axes[2].set(xlabel= "Y Position (m)", ylabel="X Position (m)")


# Colorbar for the scatter plots
cbar_verlet=fig.colorbar(scatter_noverlet, ax=axes[2], label='Velocity Magnitude (m/s) - Euler)')

cbar_noverlet=fig.colorbar(scatter_verlet, ax=axes[2], label='Velocity Magnitude (m/s) - Verlet', orientation='vertical')
cbar_noverlet.set_ticks([])

# Calculate max height and distance
def calculate_max_height_and_distance(ts, rys, rxs):
    max_height = np.max(rys)
    distance_travelled = rxs[-1]
    time_of_max_height = ts[np.argmax(rys)]
    return max_height, distance_travelled, time_of_max_height

max_height_noverlet, distance_noverlet, time_max_height_noverlet = calculate_max_height_and_distance(ts_noverlet, rys_noverlet, rxs_noverlet)
max_height_verlet, distance_verlet, time_max_height_verlet = calculate_max_height_and_distance(ts_verlet, rys_verlet, rxs_verlet)

print(f"Maximum Height (Euler Method): {max_height_noverlet:.2f} m at Time: {time_max_height_noverlet:.2f} s; Maximum Distance in Time Limit: {distance_noverlet:.2f} m,")
print(f"Maximum Height (Velocity-Verlet Method): {max_height_verlet:.2f} m at Time: {time_max_height_verlet:.2f} s; Maximum Distance in Time Limit: {distance_verlet:.2f} m,")

#This simulation models projectile motion of a particle
#(using the Euler method) allowing for bouncing with no drag effects.
#Multiple time steps can be displayed

import numpy as np
import matplotlib.pyplot as plt

import seaborn
seaborn.set_style("whitegrid")

#Input Initial Conditions
#Enter Initial X position (m) - away from origin (0,0)
rx_initial = 0
#Enter Initial Y position (m) - away from origin (0,0)
ry_initial = 10
#Enter angle of projection from horizontal (degrees)
theta_deg = 0
#Enter initial absolute velocity (metres per second)
v_initial = 0
#Enter coefficient of restitution - Fraction of energy that is conserved
#during a bounce - represented as a decimal (0.8-0.6 is typical)
cr = 0.8
#Enter simulation time (seconds)
tf= 5
#Enter multiple step sizes in seconds, seperated with commas with square
#brackets around them (e.g., [0.1, 0.01, 0.001])
dts = [0.005, 0.05, 0.5]

#constant
g = 9.81

def simulate_projectile(dt): #modelling it as a functiom of time

    t_current = 0
    theta_rad = np.radians(theta_deg)
    rx_current = rx_initial
    ry_current = ry_initial

    vx_current = v_initial * np.cos(theta_rad)
    vy_current = v_initial * np.sin(theta_rad)

    ts = [t_current]
    rxs = [rx_current]
    rys = [ry_current]
    vxs = [vx_current]
    vys = [vy_current]




    while t_current < tf :

      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt

      if ry_new <= 0: #condition for bouncing
        vx_new = vx_current
        vy_new = -cr*vy_current
        ry_new = 0
      else:

        vy_new = vy_current - g * dt

      vx_new = vx_current


      t_current += dt


      rx_current = rx_new
      ry_current = ry_new

      vx_current = vx_new
      vy_current = vy_new


      ts.append(t_current)
      rxs.append(rx_new)
      rys.append(ry_new)
      vxs.append(vx_new)
      vys.append(vy_new)

    ts = np.array(ts)
    rxs = np.array(rxs)
    rys = np.array(rys)
    vxs = np.array(vxs)
    vys = np.array(vys)
    vabs = np.sqrt(vxs**2 + vys**2)

    return ts, rxs, rys, vabs

colormaps = ['magma', 'mako', 'inferno', 'viridis', 'plasma']

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

scatter_xy_list = []


for idx, dt in enumerate(dts):
    cmap = colormaps[idx % len(colormaps)]
    ts, rxs, rys, vabs = simulate_projectile(dt)
    axes[0].scatter(ts, rxs,  c=vabs, cmap=cmap)
    axes[0].set(xlabel= "Time (s)", ylabel="X Position (m)")

    axes[1].scatter(ts, rys,  c=vabs, cmap=cmap)
    axes[1].set(xlabel= "Time (s)", ylabel="Y Position (m)")

    scatter_xy=axes[2].scatter(rxs, rys, c=vabs, cmap=cmap)
    axes[2].set(xlabel= "X Position (m)", ylabel="Y Position (m)")
    scatter_xy_list.append(scatter_xy)


#set colour bars for each angle plotted with the far right colour bar
#being the only labelled one
for idx, (scatter, dt) in enumerate(zip(scatter_xy_list, dts)):
    cbar = fig.colorbar(scatter, ax=axes, orientation='vertical', pad=0.02, fraction=0.046)
    cbar.set_label(f'Absolute Velocity (m/s) - dt = {dt} s')
    if idx > 0:
        cbar.set_ticks([])

# Calculate max height and distance
def calculate_max_height_and_distance(ts, rys, rxs):
    max_height = np.max(rys)
    distance_travelled = rxs[-1]
    time_of_max_height = ts[np.argmax(rys)]
    return max_height, distance_travelled, time_of_max_height

for dt in dts:
    ts, rxs, rys, _ = simulate_projectile(dt)
    max_height, distance_travelled, time_max_height = calculate_max_height_and_distance(ts, rys, rxs)
    print(f"Where dt= {dt:.3f} s")
    print(f"Maximum Height Reached: {max_height:.2f} m at Time: {time_max_height:.2f} s")

plt.show()

#This simulation models projectile motion of a particle
#(using the Euler method) allowing for bouncing with drag.
#Multiple densities can be displayed


import numpy as np
import matplotlib.pyplot as plt

import seaborn
seaborn.set_style("whitegrid")


#Input Initial Conditions
#Enter Initial X position (m) - away from origin (0,0)
rx_initial = 0
#Enter Initial Y position (m) - away from origin (0,0)
ry_initial = 100
#Enter angle of projection from horizontal (degrees)
theta_deg = 0
#Enter initial absolute velocity (metres per second)
v_initial = 0
#Enter one or more density of medium that particle is moving through
#(kilograms per cubic metre) - 1.225 for air, 1000 for water and 1261 for
#glycerine.
#Enter values so that they are seperated with commas with square brackets
#around the (e.g., [1, 1000])
rhos = [1.225, 1000, 1261]
#Enter mass of projectile (kg)
m = 0.000504
#Enter diameter of projectile (m)
D = 0.005
#Enter coefficient of drag for the particle (0.47 is a standard)
C_D = 0.47
#Enter coefficient of restitution - Fraction of energy that is conserved
#during a bounce - represented as a decimal (0.8-0.6 is typical)")
cr = 0.8
#Enter simulation time (seconds)
tf= 15
#Enter step size (seconds)
dt = 0.01

def simulate_projectile(dt, rho): #modelling it as a functiom of time and
#density of media

  t_current = 0
  theta_rad = np.radians(theta_deg)
  rx_current = rx_initial
  ry_current = ry_initial

  vx_current = v_initial * np.cos(theta_rad)
  vy_current = v_initial * np.sin(theta_rad)

  g = 9.81



  ts = [t_current]
  rxs = [rx_current]
  rys = [ry_current]
  vxs = [vx_current]
  vys = [vy_current]

  max_height = ry_current
  max_distance = rx_current
  terminal_velocity_reached = False
  terminal_velocity = None


  while t_current < tf :

      rx_new = rx_current + vx_current * dt
      ry_new = ry_current + vy_current * dt

      if ry_new <= 0: #condition for bouncing
            vy_new = -cr * vy_current
            ry_new = 0
      else: #effect of drag forces
            vy_new = vy_current - (g + ((1/2) * rho * vy_current * np.sqrt(vx_current**2 + vy_current**2) * ((np.pi * D**2)/4) * C_D) / m) * dt
            vx_new = vx_current - (((1/2) * rho * vx_current * np.sqrt(vx_current**2 + vy_current**2) * ((np.pi * D**2)/4) * C_D) / m ) * dt
      #checking if terminal velocity is reached and storing value if reached
      if  abs(np.sqrt(vx_new**2 + vy_new**2) - np.sqrt(vx_current**2 + vy_current**2))  < 0.0001:  # Assuming a threshold for terminal velocity - should be changed to preference
            terminal_velocity_reached = True
            terminal_velocity = np.sqrt(vx_new**2 + vy_new**2)


      t_current += dt


      rx_current = rx_new
      ry_current = ry_new

      vx_current = vx_new
      vy_current = vy_new





      ts.append(t_current)
      rxs.append(rx_new)
      rys.append(ry_new)
      vxs.append(vx_new)
      vys.append(vy_new)

      max_height = max(max_height, ry_new)
      max_distance = max(max_distance, rx_new)

  ts = np.array(ts)
  rxs = np.array(rxs)
  rys = np.array(rys)
  vxs = np.array(vxs)
  vys = np.array(vys)
  vabs = np.sqrt(vxs**2 + vys**2)


  return ts, rxs, rys, vabs, max_height, max_distance, terminal_velocity_reached, terminal_velocity


dts = [dt]

colormaps = ['magma', 'mako', 'inferno', 'viridis', 'plasma']

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

scatter_xy_list = []
max_heights = []
max_distances = []
terminal_velocities = []
#Plotting
for idx, rho in enumerate(rhos):

  terminal_velocity_reached = False
  terminal_velocity = None
  ts, rxs, rys, vabs, max_height, max_distance, terminal_velocity_reached, terminal_velocity = simulate_projectile(dt=dt, rho=rho)
  cmap = colormaps[idx % len(colormaps)]

  axes[0].scatter(ts, rxs,  c=vabs,  alpha=0.7, cmap=cmap)
  axes[0].set(xlabel= "Time (s)", ylabel="X Position (m)")
  axes[0].set_ylim(bottom=0)
  axes[0].set_xlim(left=0)

  axes[1].scatter(ts, rys,  c=vabs,  alpha=0.7, cmap=cmap)
  axes[1].set(xlabel= "Time (s)", ylabel="Y Position (m)")
  axes[1].set_ylim(bottom=0)
  axes[1].set_xlim(left=0)

  scatter_xy = axes[2].scatter(rxs, rys, c=vabs,  alpha=0.7, cmap=cmap)
  axes[2].set(xlabel= "X Position (m)", ylabel="Y Position (m)")
  axes[2].set_ylim(bottom=0)
  axes[2].set_xlim(left=0)
  scatter_xy_list.append(scatter_xy)


# Display max height, distance and terminal velocity
  print(f"Density: {rho} kg/m\u00b3")
  print(f"Maximum Height Reached: {max_height:.2f} m")
  print(f"Maximum Distance in Time Limit: {max_distance:.2f} m")
  if terminal_velocity_reached:
      print(f"Terminal velocity was reached during the simulation: {terminal_velocity:.2f} m/s")

  else:
      print("Terminal velocity was not reached during the simulation.")

#set colour bars for each density plotted with the far right colour bar
#being the only labelled one
for idx, (scatter, rho) in enumerate(zip(scatter_xy_list, rhos)):
    cbar = fig.colorbar(scatter, ax=axes, orientation='vertical', pad=0.02, fraction=0.046)
    cbar.set_label(f'Absolute Velocity (m/s) - Density of medium = {rhos[idx]} kg/m\u00b3')
    if idx > 0:
        cbar.set_ticks([])

plt.show()